sudo: false

language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - make

env:
  - $COVPYYAML=cov41-pyyaml,coveralls41

script:
  # Tests
  - python -m unittest discover -v
  # Style checks
  - pylint train/experience.py
  # Coverage checks
  - py.test --cov=train tests/

after_success:
  coveralls

notifications:
  email:
    on_success: change
    on_failure: change
