sudo: false

language: python

python:
  - 3.5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  global:
    - CXX=g++-4.9

install:
  - pip install -r requirements.txt
  - make

script:
  # Tests
  - python -m unittest discover -v
  # Style checks
  # Temporary workaround
  - for i in `cat pylint_checks.txt` ; do pylint $i ;done

  # Coverage checks
  - py.test --cov=train tests/

after_success:
  coveralls

notifications:
  email:
    on_success: change
    on_failure: change
