sudo: false

language: python

python:
  - 3.5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  global:
    - CXX=g++-4.9

install:
  - pip install -r requirements.txt
  - make

script:
  # Tests
 - python -m unittest discover -v
 - find . -iname "*.py" | xargs pylint

  # Coverage checks
 - python networking/start_game.py -sp "OpponentBot.py"
 - py.test --cov=train tests/

after_success:
  coveralls

notifications:
  email:
    on_success: change
    on_failure: change
